apiVersion: apps/v1
kind: Deployment
metadata:
  name: sp-deployment
  labels:
    app: sp
spec:
  replicas: 0  # Adjust the number of replicas as per your requirements
  selector:
    matchLabels:
      app: sp
  replicas: 0
  template:
    metadata:
      labels:
        app: sp
    spec:
      containers:
        - name: sp
          image: ahussain900/sp:latest  # Replace with your Docker image URL
          ports:
            - containerPort: 8080  # Port that your sp application listens on
---
apiVersion: v1
kind: Service
metadata:
  name: sp-service
spec:
  type: NodePort
  selector:
    app: sp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
